bima_policy/urls.py
from django.urls import path,re_path
from bima_policy.models import *
from .views import *
app_name='bima_policy'
urlpatterns = [
    path('login/', loginView, name='login'),
    path('logout/', logout, name='logout'),
    path('profile/',Profile,name='profile'),
    path('dashboard/',dashboard , name='dashboard'),
    path('profile/bank_details/',bank_details,name='bank_det'),  
    path('profile/bank_details/<str:id>',delete_bank_details,name='del_bank'),
    path('user/',staffmanage, name='staff'),
    path('user/edit/<str:id>',staff_edit,name='staff_edit'),
    path('agent/',agent, name='agent'),
    path('agent/add_agent/',add_agent, name='add_agent'),
    path('agent/profile',agent_profile , name='agent_profile'),
    path('service_provider/', service_provider, name='service_p'),
    path('service_provider/add_sp/', add_sp, name='add_sp'),
    path('service_provider/<str:id>/delete', delete_sp, name='del_sp'),
    path('service_provider/<str:id>/edit', edit_sp, name='edit_sp'),
    path('service_provider/broker/<str:id>/del',del_broker_code, name='del_broker_code'),
    path('vehicle/',vehicle_view, name='vehi'),
    path('vehicle/<str:id>',delete_vehicle,name='del_vehicle'),
    path('vehicle/<str:id>/edit',edit_vehicle,name='edit_vehicle'),
    path('insurance_comp/', ins_comp, name="ins_comp"),
    path('insurance_comp/<str:id>',ins_del, name='ins_del'),
    path('rto/',rto_list , name="rto"),
    path('rto/<str:id>',update_rto, name='rto_delete'),
    path('slab/', slab, name="slab"),
    path('slab/<str:id>',slab_delete,name="del_slab"),
    path('slab/<str:id>/edit',slab_edit,name="edit_slab"),
    path('slab/slab_payoutlist/<str:id>', slab_payout, name="slab_payout"),
    path('slab/slab_payoutform/',slab_payoutform, name="slab_payoutform"),
    path('slab/slab_payoutlist/payout/<str:id>/delete',payout_delete, name="payout_delete"),
    path('slab/slab_payoutlist/payout/<str:id>/edit',payout_edit, name="payout_edit"),
    path('policy/',create_policy.as_view(), name="create_policy"),
    path('policy/entry',policy_entry, name="policy_entry"),
    path('policy/<str:id>/delete',policy_delete, name="policy_delete"),
    path('policy/edit/<str:id>', edit_policy,name="edit_policy"),
    path('policy/import',policy_import, name="policy_import"),
    path('upcomingRenewal/',upcoming_renewal, name="upcoming_renewal"),
    path('agent_payable/',agentpayable, name="agentpayable"),
    path('agent_statement/',agent_statement, name="agent_statement"),
    path('SP_receive/',sp_receivable, name="sp_receivable"),
    path('SP_statement/',sp_statement, name="sp_statement"),
    path('report_agent/',report_agent, name="report_agent"),
    path('report_PP/',report_policyprovider, name="report_policyprovider"),
    path('report_Vcat/',report_vehicleCategory, name="report_vehicleCategory"),
    path('report_broker/',report_brokercode, name="report_brokercode"),
    path('report_insurance/',report_insurance_comp, name="report_insurance_comp"),
    path('subscription/',subscription, name="subscription"),
]

bima_policy/forms.py
# from django import forms
# from .models import RtoConversionModel  

# class RtoForm(forms.ModelForm):
#     class Meta:
#         model = RtoConversionModel
#         fields = ['rto_series','rto_return','status']  
#         widgets = {
#             'rto_series': forms.TextInput(attrs={'class':'form-control','id':'nameid'}),
#             'rto_return': forms.TextInput(attrs={'class':'form-control','id':'nameid'}),
#             'status': forms.TextInput(attrs={'class':'form-control','id':'nameid'}),
#         }

bima_policy/views.py
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404,render
from django.shortcuts import redirect,render
from django.contrib import messages
from django.views import View
from .models import *
from .forms import *


def get_id_from_session(request):
    id=request.session['id']
    return id
def Index(request):
     return render(request, 'index.html')


# DashBoardView
def dashboard(request):
    agentcount=Agents.objects.filter(profile_id=get_id_from_session(request)).count()
    staffcount=StaffModel.objects.filter(profile_id=get_id_from_session(request)).count()
    spcount=ServiceProvider.objects.filter(profile_id=get_id_from_session(request)).count()
    policycount=Agents.objects.filter(profile_id=get_id_from_session(request)).count()
    print('total agents are:',agentcount)
    return render(request,'dashboard.html',{'agentcount':agentcount,'staffcount':staffcount,'spcount':spcount,'totalpolicy':policycount})


#LoginView
def login_form(request):
    return render(request,'login.html')
def loginView(request):
    try:
        if request.method=='POST':
            full_name = request.POST['full_name']
            password = request.POST['password']
            user=ProfileModel.objects.filter(full_name=full_name,password=password).first()
            user1=Agents.objects.filter(login_id=full_name,password=password).first()
            user2=StaffModel.objects.filter(login_id =full_name,password=password).first()
            if user:
                p=ProfileModel.objects.filter(full_name=full_name,password=password).first()
                id = p.id
                request.session['id']=user.id
                request.session['full_name']=user.full_name
                userr_ob = UserRole.objects.filter(profile_id=id)
                if userr_ob:
                    pass
                else:
                    UserRole.objects.create(profile_id_id = id, role='admin')
                return redirect('bima_policy:dashboard')
            if user1:
                id = request.session['id']=user1.login_id
                request.session['full_name']=user1.full_name
                # user_ob = UserRole.objects.filter(agent_id=id).first()
                # role = user_ob.role
                request.session["role"] = "agent"
                return redirect('bima_policy:dashboard')
            if user2:
                request.session['id']=user2.login_id
                request.session['staffname']=user2.staffname
                request.session["role"] = "staff"
                return redirect('bima_policy:dashboard')
            return render(request,'login.html',{'error_message':'Invalid ID or Password!'})
    except (ProfileModel.DoesNotExist,Agents.DoesNotExist,StaffModel.DoesNotExist):
        error_message='Invalid ID or Password!'
        return render(request,'login.html',{'error_message':error_message})


# ProfileView
def Profile(request):
    if request.method=="GET":
        try:
            data = ProfileModel.objects.filter(id=get_id_from_session(request))
            return render(request, 'profile/profile.html',{'data':data})
        except ProfileModel.DoesNotExist:
            return HttpResponse('Profile does not exist.')
    elif request.method=='POST' and 'updpassword' in request.POST:
        try:
            profile=ProfileModel.objects.filter(id=get_id_from_session(request))
            password=request.POST['password']
            profile.update(password=password)
            return render(request,'login.html',{'success_message':'Password update successfully!'})
        except ProfileModel.DoesNotExist:
            return HttpResponse('Profile does not exist.')



# UserView
def staffmanage(request):
    if request.method=='GET':
        try:
            data = StaffModel.objects.filter(profile_id=get_id_from_session(request))
            return render(request, 'user/user.html',{'data':data})
        except StaffModel.DoesNotExist:
            return render(request, 'user/user.html')
    else:
        if 'staff_add' in request.POST:
            data = ProfileModel.objects.get(id=get_id_from_session(request))
            staffname=request.POST['staffname']
            password=request.POST['password']
            StaffModel.objects.create(staffname=staffname,password=password,profile_id=data)
            return HttpResponseRedirect(request.path,('staff'))

def staff_edit(request,id):
    if request.method=='GET':
        try:
            data = StaffModel.objects.filter(login_id=id)
            return render(request, 'user/user_edit.html',{'data':data})
        except StaffModel.DoesNotExist:
            return render(request, 'user/user_edit.html')
    else:
        if 'profile' in request.POST:
            StaffModel.objects.filter(login_id=id).update(staffname=request.POST['full_name'],status=request.POST['status'])
        return redirect('bima_policy:staff')


# ProfileView
def bank_details(request):
    if request.method=="GET":
        try:
            data={}
            pdata = ProfileModel.objects.filter(id=get_id_from_session(request))
            bdata = BankDetail.objects.filter(profile_id_id=get_id_from_session(request))
            return render(request, 'profile/bank_details.html' , {'pdata':pdata,'bdata':bdata})
        except BankDetail.DoesNotExist:
            return render(request, 'profile/bank_details.html')
    else:
        try:
            if "bankadd" in request.POST:
                data = ProfileModel.objects.get(id=get_id_from_session(request))
                beneficiary_name=request.POST['beneficiary_name']
                acc_no=request.POST['account_number']
                bank_name=request.POST['bank_name']
                BankDetail.objects.create(beneficiary_name=beneficiary_name, acc_no=acc_no,bank_name=bank_name, profile_id=data)
                return HttpResponseRedirect(request.path,('bank_det'))
        except ProfileModel.DoesNotExist:
            return HttpResponse('error')
    return HttpResponseRedirect(request.path,('bank_det'))  

def delete_bank_details(request,id):
    if request.method=="GET":
        return redirect('bima_policy:bank_det')
    else:
        if "delete" in request.POST:
            # obj=BankDetail.objects.filter(id=id)
            #obj.delete()
            get_object_or_404(BankDetail, id=id).delete()
            return redirect('bima_policy:bank_det')

def change_password(request):
    if request.method=='POST' and 'updpassword' in request.POST:
        profile=ProfileModel.objects.filter(id=get_id_from_session(request))
        password=request.POST['password']
        profile.update(password=password)


# RTOView
def rto_list(request):
    if request.method=="GET":
        data=RtoConversionModel.objects.filter(profile_id_id=get_id_from_session(request))
        return render(request, 'rto/RTO.html', {'data': data})
    if request.method=="POST" and 'rto_add' in request.POST:
        data = ProfileModel.objects.get(id=get_id_from_session(request))
        rtoseries=request.POST['rtoseries']
        rtoreturn=request.POST['rtoreturn']
        RtoConversionModel.objects.create(rto_series=rtoseries,rto_return=rtoreturn,profile_id=data)
        return redirect('bima_policy:rto')

def update_rto(request,id):
    data={}
    if request.method=="GET":
        data = RtoConversionModel.objects.filter(profile_id_id=get_id_from_session(request))
        udata=RtoConversionModel.objects.filter(id=id)
        return render(request, 'RTO.html',{'data':data,'udata':udata})
    if request.method=='POST':
        if "delete" in request.POST:
            item = get_object_or_404(RtoConversionModel, id=id)
            item.delete()
            return redirect('bima_policy:rto')


# InsuranceView
def ins_comp(request):
    if request.method=="GET":
        try:
            data=InsuranceCompany.objects.filter(profile_id=get_id_from_session(request))
            return render(request,'insurancecompany/insurance_comp.html', {'data':data})
        except ProfileModel.DoesNotExist:
            return render(request,'insurancecompany/insurance_comp.html')
    elif 'company_add' in request.POST:
        try:
            data=ProfileModel.objects.get(id=get_id_from_session(request))
            ins_name=request.POST['inscomp_name']
            status=request.POST['status']
            InsuranceCompany.objects.create(comp_name=ins_name,status=status,profile_id=data)
            return redirect('bima_policy:ins_comp')
        except ProfileModel.DoesNotExist:
            return HttpResponseRedirect(request.path,('bank_det'))

def ins_del(request,id):
    if request.method=='POST' and 'delete' in request.POST:
        data=InsuranceCompany.objects.filter(id=id)
        data.delete()
        return redirect('bima_policy:ins_comp')


# VehicleView
def vehicle_view(request):
    if request.method=="GET":
        try:
            data=VehicleMakeBy.objects.filter(profile_id_id=get_id_from_session(request))
            datamn=VehicleModelName.objects.filter(profile_id_id=get_id_from_session(request))
            datavc=VehicleCategory.objects.filter(profile_id_id=get_id_from_session(request))
            mylist=zip(datamn,data)
            return render(request,'vehicle/vehicle.html',{'list':mylist, 'datavc':datavc, 'data':data,'datamn':datamn})
        except(VehicleMakeBy.DoesNotExist,VehicleModelName.DoesNotExist,VehicleCategory.DoesNotExist):
            return render(request,'vehicle/vehicle.html')
    else:
        p= ProfileModel.objects.get(id=get_id_from_session(request))
        if 'mb_add' in request.POST:
            VehicleMakeBy.objects.create(company=request.POST['makeby'],status = request.POST['mbstatus'],profile_id=p)
            return redirect('bima_policy:vehi')
        elif 'vm_add' in request.POST:

bima_policy/templates/payout/payoutname_edit.html
{%extends "base.html"%}
{%block content%}
{% load static %}
<main class="app-main"><!-- .app-main -->
    <div class="wrapper"><!-- .wrapper -->
        <div class="page "><!-- .page -->
            <div class="page-inner"> <!-- .page-inner -->
                <header class="page-title-bar"><!-- .page-title-bar -->
                <div class="d-flex justify-content-between align-items-center"><!-- .d-flex -->
                    <!-- .breadcrumb -->
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item active">
                                <a href="{%url 'bima_policy:slab'%}"><i class="breadcrumb-icon fa fa-angle-left mr-2"></i>Back</a>
                            </li>
                        </ol>
                    </nav><!-- /.breadcrumb -->
                </div><!-- /.d-flex -->
                <!-- grid row -->
                <div class="row text-center text-sm-left">
                </div>
                </header>
                <!-- .page-section -->
                <div class="col-md-5 mb-3">
                    <!-- grid row -->
                    <div class="modal-content">
                        <div class="modal-header">
                            <h6 id="ModalLabel" class="modal-title">Update Slab Name</h6>
                        </div>
                        {%for value in data%}
                        <form method="post">
                            {% csrf_token %}
                            <div class="modal-body">
                                <div class="form-group">
                                    <label class="col-form-label">Slab Name<em class="text-danger">*</em></label>
                                    <input type="text" class="form-control" data-parsley-required="true" id="slab_name", name="slab_name", value="{{value.slab_name}}">
                                    <input type="hidden" id="vcid" name="vcid" data-parsley-required="true" readonly="" value="28">
                                </div>
                                <div class="form-group">
                                    <label class="form-label">Status</label>
                                    <select name="status" id="status" class="custom-select">
                                        <option value="Active">Active</option>
                                        <option value="Inactive">Inactive</option>
                                    </select>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary w-100p" data-dismiss="modal">Close</button>
                                <button type="submit" name="slab_update" class="btn btn-primary w-100p">Update</button>
                            </div>
                        </form>
                        {%endfor%}
                    </div>
                </div><!-- /.page-section -->
            </div><!-- /.page-inner -->
        </div><!-- /.page -->
    </div><!-- /.wrapper -->
</main>
{%endblock%}

bima_policy/templates/payout/slab_payoutlist.html
{%extends "base.html"%}
{%block content%}
{% load static %}
<main class="app-main">
   <!-- .wrapper -->
   <div class="wrapper">
      <div class="page-inner">
         <!-- .page-inner -->
         <header class="page-title-bar">
            <nav aria-label="breadcrumb">
               <ol class="breadcrumb">
                  <li class="breadcrumb-item">
                     <a href="{%url 'bima_policy:slab'%}"><i class="breadcrumb-icon fa fa-angle-left mr-2"></i>Payout Slabs</a>
                  </li>
                  <li class="breadcrumb-item active">
                     {% for value in data1 %}
                     <a href="javascript:void(0);"></a>
                     {% endfor %}
                  </li>
               </ol>
            </nav>
            <h1 class="page-title"> Payout List 
               <button class="btn btn-secondary btn-sm float-right" id="download_payout" onclick="ExportToExcel('xlsx')"><i class="fa fa-download"></i> Download</button>
               <a href="{%url 'bima_policy:slab_payoutform' %}" class="btn btn-secondary btn-sm float-right mr-2"><i class="fa fa-plus"></i> Add New</a>
            </h1>
         </header>
         <!-- .page-section -->
         <div class="page-section">
            <!-- .card -->
            <div class="card card-fluid">
               <!-- .card-body -->
               <div class="card-body">
                  <!-- .table -->
                  <div class="table-responsive">
                     <div id="tblList_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                        <div class="row">
                           <div class="col-sm-12 col-md-6">
                              <div class="dataTables_length" id="tblList_length">
                                 <label>
                                    Show 
                                    <select name="tblList_length" aria-controls="tblList" class="custom-select">
                                       <option value="10">10</option>
                                       <option value="25">25</option>
                                       <option value="50">50</option>
                                       <option value="100">100</option>
                                    </select>
                                    entries
                                 </label>
                              </div>
                           </div>
                           <div class="col-sm-12 col-md-6">
                              <div id="tblList_filter" class="dataTables_filter"><label>Search:<input type="search" class="form-control" placeholder="" aria-controls="tblList"></label></div>
                           </div>
                        </div>
                        <div class="table-responsive">
                           <table id="tblList" class="table nowrap dataTable no-footer" role="grid" aria-describedby="tblList_info">
                              <thead>
                                 <tr role="row">
                                    <th class="text-center w-10pc sorting_asc" tabindex="0" aria-controls="tblList" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Sr. No.: activate to sort column descending" style="width: 0px;">Sr. No.</th>
                                    <th class="sorting" tabindex="0" aria-controls="tblList" rowspan="1" colspan="1" aria-label="Payout Name: activate to sort column ascending" style="width: 0px;">Payout Name</th>
                                    <th class="sorting" tabindex="0" aria-controls="tblList" rowspan="1" colspan="1" aria-label="Case Type: activate to sort column ascending" style="width: 0px;">Case Type</th>
                                    <th class="sorting" tabindex="0" aria-controls="tblList" rowspan="1" colspan="1" aria-label="Coverage: activate to sort column ascending" style="width: 0px;">Coverage</th>
                                    <th class="sorting" tabindex="0" aria-controls="tblList" rowspan="1" colspan="1" aria-label="Fuel Type: activate to sort column ascending" style="width: 0px;">Fuel Type</th>
                                    <th class="sorting" tabindex="0" aria-controls="tblList" rowspan="1" colspan="1" aria-label="CPA: activate to sort column ascending" style="width: 0px;">CPA</th>
                                    <th class="text-center sorting" tabindex="0" aria-controls="tblList" rowspan="1" colspan="1" aria-label="Reward On: activate to sort column ascending" style="width: 0px;">Reward On</th>
                                    <th class="text-center sorting" tabindex="0" aria-controls="tblList" rowspan="1" colspan="1" aria-label="Reward %age: activate to sort column ascending" style="width: 0px;">Reward %age</th>
                                    <th class="text-center sorting" tabindex="0" aria-controls="tblList" rowspan="1" colspan="1" aria-label="Self Reward On: activate to sort column ascending" style="width: 0px;">Self Reward On</th>
                                    <th class="text-center sorting" tabindex="0" aria-controls="tblList" rowspan="1" colspan="1" aria-label="Self Reward %age: activate to sort column ascending" style="width: 0px;">Self Reward %age</th>
                                    <th class="text-center sorting" tabindex="0" aria-controls="tblList" rowspan="1" colspan="1" aria-label="Status: activate to sort column ascending" style="width: 0px;">Status</th>
                                    <th class="text-center sorting_disabled" rowspan="1" colspan="1" aria-label="#" style="width: 0px;">#</th>
                                 </tr>
                              </thead>
                              {%for value in data1%}
                              <tbody>
                                 <tr role="row" class="odd">
                                    <td class="text-center w-10pc sorting_1">{{forloop.counter}}</td>
                                    <td><a href="{%url 'bima_policy:slab_payoutform'%}">{{value.payout_name}}</a></td>
                                    <td>{{value.case_type}}</td>
                                    <td>{{value.coverage}}</td>
                                    <td>{{value.fuel_type}}</td>
                                    <td>{{value.cpa}}</td>
                                    <td class=" text-center ">{{value.rewards_on}}</td>
                                    <td class=" text-center ">{{value.rewards_age}}</td>
                                    <td class=" text-center ">{{value.self_rewards_on}}</td>
                                    <td class=" text-center ">{{value.self_rewards_age}}</td>
                                    <td class=" text-center "><span class="badge badge-success">{{value.status}}</span></td>
                                    <td class=" text-center">
                                       <form method="post">
                                          {% csrf_token %}
                                          <a href="{%url 'bima_policy:payout_edit' value.payoutid %}" class="mr-1 btn btn-sm btn-icon btn-secondary" title="Edit">
                                          <i class="fa fa-pencil-alt mt-2" aria-hidden="true"></i>
                                          </a>
                                          <a href="{%url 'bima_policy:payout_delete' value.payoutid %}" class="mr-1 btn btn-sm btn-icon btn-secondary " title="Remove">
                                          <i class="fa fa-trash-alt text-danger mt-2" aria-hidden="true"></i>
                                          </a>
                                       </form>
                                    </td>
                                 </tr>
                              </tbody>
                              {%endfor%}
                           </table>
                        </div>
                        <div class="row align-items-center">
                           <div class="col-sm-12 col-md-5">
                              <div class="dataTables_info" id="tblList_info" role="status" aria-live="polite">Showing 1 to 1 of 1 entries</div>
                           </div>
                           <div class="col-sm-12 col-md-7 d-flex justify-content-end">
                              <div class="dataTables_paginate paging_simple_numbers" id="tblList_paginate">
                                 <ul class="pagination justify-content-center">
                                    <li class="paginate_button page-item previous disabled" id="tblList_previous"><a href="#" aria-controls="tblList" data-dt-idx="0" tabindex="0" class="page-link"><i class="fa fa-lg fa-angle-left"></i></a></li>
                                    <li class="paginate_button page-item active"><a href="#" aria-controls="tblList" data-dt-idx="1" tabindex="0" class="page-link">1</a></li>
                                    <li class="paginate_button page-item next disabled" id="tblList_next"><a href="#" aria-controls="tblList" data-dt-idx="2" tabindex="0" class="page-link"><i class="fa fa-lg fa-angle-right"></i></a></li>
                                 </ul>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <!-- /.card-body -->
            </div>
            <!-- /.card -->
            <div class="modal fade" id="mdlpayout" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="SlabrTitle" aria-hidden="true">
               <div class="modal-dialog" role="document">
                  <div class="modal-content">
                     <div class="modal-header">
                        <h5 id="SlabrTitle" class="modal-title">Confirmation</h5>
                     </div>
                     <div class="modal-body">
                        <input type="hidden" id="payout_id">
                        <p>Do you want to delete selected payout?</p>
                     </div>
                     <div class="modal-footer">
                        <button type="button" class="btn btn-secondary w-100p" data-dismiss="modal">No</button>
                        <button type="submit" id="payout_remove" class="btn btn-primary w-100p">Yes</button>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <!-- /.page-section -->
      </div>
   </div>
   <!-- /.wrapper -->
</main>
<!-- /.app-main -->
<div class="aside-backdrop"></div>
</div><!-- /.app -->
<div class="modal modal-alert fade" id="ModalAlertError" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="ModalAlertErrorLabel" aria-hidden="true">
   <!-- .modal-dialog -->
   <div class="modal-dialog" role="document">
      <!-- .modal-content -->
      <div class="modal-content">
         <!-- .modal-header -->
         <div class="modal-header">
            <h5 class="modal-title">
               <i class="fa fa-exclamation-triangle text-red mr-1"></i> System Error 
            </h5>
         </div>
         <!-- /.modal-header -->
         <!-- .modal-body -->
         <div class="modal-body">
            <p>The Code Execution cannot proceed due to system error, retry after refreshing the page if the error remains the same, you need to contact your Administrator immediately.</p>
         </div>
         <!-- /.modal-body -->
         <!-- .modal-footer -->
         <div class="modal-footer">
            <button type="button" class="btn btn-light" data-dismiss="modal">OK</button>
         </div>
         <!-- /.modal-footer -->
      </div>
      <!-- /.modal-content -->
   </div>
   <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
<!-- BEGIN BASE JS -->
{% comment %} <script src="{%static 'js/jquery.min.js' %}"></script>
<script src="{%static 'js/popper.min.js' %}"></script>
<script src="{%static 'js/bootstrap.min.js' %}"></script> <!-- END BASE JS -->
<!-- BEGIN PLUGINS JS -->
<script src="{% static 'js/pace.min.js' %}"></script>
<script src="{% static 'js/stacked-menu.min.js' %}"></script>
<script src="{% static 'js/perfect-scrollbar.min.js'%}"></script> <!-- END PLUGINS JS -->
<!-- Parsley -->
<script src="{%static 'js/parsley.js' %}"></script>
<!-- BEGIN THEME JS -->
<script src="{%static 'js/theme.js' %}"></script> 
<script src="{%static 'js/toastr.min.js' %}"></script>
<script src="{%static 'js/flatpickr.min.js' %}"></script>
<script src="{%static 'js/select2.full.min.js' %}"></script>
<script src="{%static 'js/moment.js' %}"></script>
<script src="{%static 'js/mask-as-number.min.js' %}"></script>
<script src="{%static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{%static 'js/dataTables.bootstrap.js' %}"></script>
<script src="{%static 'js/jquery.form.js' %}"></script>
<script src="{%static 'js/custom.min.js' %}"></script>
{% comment %} <script src="{%static 'js/slab.min.js' %}"></script> {% endcomment %}
{% comment %} <script>
   $("#download_payout").click(function(){
   $.redirectPost("download.php",{download:'download_payout',slab:"25"});
   });
</script>
</body></html>  {% endcomment %}
<script type="text/javascript" src="https://unpkg.com/xlsx@0.15.1/dist/xlsx.full.min.js"></script>
<script>
  function ExportToExcel(type, fn, dl) {
    var elt = document.getElementById('tblList');
    var wb = XLSX.utils.table_to_book(elt, { sheet: "sheet1" });
    return dl ?
      XLSX.write(wb, { bookType: type, bookSST: true, type: 'base64' }):
      XLSX.writeFile(wb, fn || ('MySheetName.' + (type || 'xlsx')));
 }
</script>
{%endblock%}