bima_policy/urls.py
from django.urls import path,re_path
from bima_policy.models import *
from .views import *
app_name='bima_policy'
urlpatterns = [
    path('login/', loginView, name='login'),
    path('logout/', logout, name='logout'),
    path('profile/',Profile,name='profile'),
    path('dashboard/',dashboard , name='dashboard'),
    path('profile/bank_details/',bank_details,name='bank_det'),  
    path('profile/bank_details/<str:id>',delete_bank_details,name='del_bank'),
    path('user/',staffmanage, name='staff'),
    path('user/edit/<str:id>',staff_edit,name='staff_edit'),
    path('agent/',agent, name='agent'),
    path('agent/add_agent/',add_agent, name='add_agent'),
    path('agent/profile',agent_profile , name='agent_profile'),
    path('service_provider/', service_provider, name='service_p'),
    path('service_provider/add_sp/', add_sp, name='add_sp'),
    path('service_provider/<str:id>/delete', delete_sp, name='del_sp'),
    path('service_provider/<str:id>/edit', edit_sp, name='edit_sp'),
    path('service_provider/broker/<str:id>/del',del_broker_code, name='del_broker_code'),
    path('vehicle/',vehicle_view, name='vehi'),
    path('vehicle/<str:id>',delete_vehicle,name='del_vehicle'),
    path('vehicle/<str:id>/edit',edit_vehicle,name='edit_vehicle'),
    path('insurance_comp/', ins_comp, name="ins_comp"),
    path('insurance_comp/<str:id>',ins_del, name='ins_del'),
    path('rto/',rto_list , name="rto"),
    path('rto/<str:id>',update_rto, name='rto_delete'),
    path('slab/', slab, name="slab"),
    path('slab/<str:id>',slab_delete,name="del_slab"),
    path('slab/<str:id>/edit',slab_edit,name="edit_slab"),
    path('slab/slab_payoutlist/<str:id>', slab_payout, name="slab_payout"),
    path('slab/slab_payoutform/',slab_payoutform, name="slab_payoutform"),
    path('slab/slab_payoutlist/payout/<str:id>/delete',payout_delete, name="payout_delete"),
    path('slab/slab_payoutlist/payout/<str:id>/edit',payout_edit, name="payout_edit"),
    path('policy/',create_policy.as_view(), name="create_policy"),
    path('policy/entry',policy_entry, name="policy_entry"),
    path('policy/<str:id>/delete',policy_delete, name="policy_delete"),
    path('policy/edit/<str:id>', edit_policy,name="edit_policy"),
    path('policy/import',policy_import, name="policy_import"),
    path('upcomingRenewal/',upcoming_renewal, name="upcoming_renewal"),
    path('agent_payable/',agentpayable, name="agentpayable"),
    path('agent_statement/',agent_statement, name="agent_statement"),
    path('SP_receive/',sp_receivable, name="sp_receivable"),
    path('SP_statement/',sp_statement, name="sp_statement"),
    path('report_agent/',report_agent, name="report_agent"),
    path('report_PP/',report_policyprovider, name="report_policyprovider"),
    path('report_Vcat/',report_vehicleCategory, name="report_vehicleCategory"),
    path('report_broker/',report_brokercode, name="report_brokercode"),
    path('report_insurance/',report_insurance_comp, name="report_insurance_comp"),
    path('subscription/',subscription, name="subscription"),
]

bima_policy/forms.py
# from django import forms
# from .models import RtoConversionModel  

# class RtoForm(forms.ModelForm):
#     class Meta:
#         model = RtoConversionModel
#         fields = ['rto_series','rto_return','status']  
#         widgets = {
#             'rto_series': forms.TextInput(attrs={'class':'form-control','id':'nameid'}),
#             'rto_return': forms.TextInput(attrs={'class':'form-control','id':'nameid'}),
#             'status': forms.TextInput(attrs={'class':'form-control','id':'nameid'}),
#         }

bima_policy/views.py
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404,render
from django.shortcuts import redirect,render
from django.contrib import messages
from django.views import View
from .models import *
from .forms import *


def get_id_from_session(request):
    id=request.session['id']
    return id
def Index(request):
     return render(request, 'index.html')


# DashBoardView
def dashboard(request):
    agentcount=Agents.objects.filter(profile_id=get_id_from_session(request)).count()
    staffcount=StaffModel.objects.filter(profile_id=get_id_from_session(request)).count()
    spcount=ServiceProvider.objects.filter(profile_id=get_id_from_session(request)).count()
    policycount=Agents.objects.filter(profile_id=get_id_from_session(request)).count()
    print('total agents are:',agentcount)
    return render(request,'dashboard.html',{'agentcount':agentcount,'staffcount':staffcount,'spcount':spcount,'totalpolicy':policycount})


#LoginView
def login_form(request):
    return render(request,'login.html')
def loginView(request):
    try:
        if request.method=='POST':
            full_name = request.POST['full_name']
            password = request.POST['password']
            user=ProfileModel.objects.filter(full_name=full_name,password=password).first()
            user1=Agents.objects.filter(login_id=full_name,password=password).first()
            user2=StaffModel.objects.filter(login_id =full_name,password=password).first()
            if user:
                p=ProfileModel.objects.filter(full_name=full_name,password=password).first()
                id = p.id
                request.session['id']=user.id
                request.session['full_name']=user.full_name
                userr_ob = UserRole.objects.filter(profile_id=id)
                if userr_ob:
                    pass
                else:
                    UserRole.objects.create(profile_id_id = id, role='admin')
                return redirect('bima_policy:dashboard')
            if user1:
                id = request.session['id']=user1.login_id
                request.session['full_name']=user1.full_name
                # user_ob = UserRole.objects.filter(agent_id=id).first()
                # role = user_ob.role
                request.session["role"] = "agent"
                return redirect('bima_policy:dashboard')
            if user2:
                request.session['id']=user2.login_id
                request.session['staffname']=user2.staffname
                request.session["role"] = "staff"
                return redirect('bima_policy:dashboard')
            return render(request,'login.html',{'error_message':'Invalid ID or Password!'})
    except (ProfileModel.DoesNotExist,Agents.DoesNotExist,StaffModel.DoesNotExist):
        error_message='Invalid ID or Password!'
        return render(request,'login.html',{'error_message':error_message})


# ProfileView
def Profile(request):
    if request.method=="GET":
        try:
            data = ProfileModel.objects.filter(id=get_id_from_session(request))
            return render(request, 'profile/profile.html',{'data':data})
        except ProfileModel.DoesNotExist:
            return HttpResponse('Profile does not exist.')
    elif request.method=='POST' and 'updpassword' in request.POST:
        try:
            profile=ProfileModel.objects.filter(id=get_id_from_session(request))
            password=request.POST['password']
            profile.update(password=password)
            return render(request,'login.html',{'success_message':'Password update successfully!'})
        except ProfileModel.DoesNotExist:
            return HttpResponse('Profile does not exist.')



# UserView
def staffmanage(request):
    if request.method=='GET':
        try:
            data = StaffModel.objects.filter(profile_id=get_id_from_session(request))
            return render(request, 'user/user.html',{'data':data})
        except StaffModel.DoesNotExist:
            return render(request, 'user/user.html')
    else:
        if 'staff_add' in request.POST:
            data = ProfileModel.objects.get(id=get_id_from_session(request))
            staffname=request.POST['staffname']
            password=request.POST['password']
            StaffModel.objects.create(staffname=staffname,password=password,profile_id=data)
            return HttpResponseRedirect(request.path,('staff'))

def staff_edit(request,id):
    if request.method=='GET':
        try:
            data = StaffModel.objects.filter(login_id=id)
            return render(request, 'user/user_edit.html',{'data':data})
        except StaffModel.DoesNotExist:
            return render(request, 'user/user_edit.html')
    else:
        if 'profile' in request.POST:
            StaffModel.objects.filter(login_id=id).update(staffname=request.POST['full_name'],status=request.POST['status'])
        return redirect('bima_policy:staff')


# ProfileView
def bank_details(request):
    if request.method=="GET":
        try:
            data={}
            pdata = ProfileModel.objects.filter(id=get_id_from_session(request))
            bdata = BankDetail.objects.filter(profile_id_id=get_id_from_session(request))
            return render(request, 'profile/bank_details.html' , {'pdata':pdata,'bdata':bdata})
        except BankDetail.DoesNotExist:
            return render(request, 'profile/bank_details.html')
    else:
        try:
            if "bankadd" in request.POST:
                data = ProfileModel.objects.get(id=get_id_from_session(request))
                beneficiary_name=request.POST['beneficiary_name']
                acc_no=request.POST['account_number']
                bank_name=request.POST['bank_name']
                BankDetail.objects.create(beneficiary_name=beneficiary_name, acc_no=acc_no,bank_name=bank_name, profile_id=data)
                return HttpResponseRedirect(request.path,('bank_det'))
        except ProfileModel.DoesNotExist:
            return HttpResponse('error')
    return HttpResponseRedirect(request.path,('bank_det'))  

def delete_bank_details(request,id):
    if request.method=="GET":
        return redirect('bima_policy:bank_det')
    else:
        if "delete" in request.POST:
            # obj=BankDetail.objects.filter(id=id)
            #obj.delete()
            get_object_or_404(BankDetail, id=id).delete()
            return redirect('bima_policy:bank_det')

def change_password(request):
    if request.method=='POST' and 'updpassword' in request.POST:
        profile=ProfileModel.objects.filter(id=get_id_from_session(request))
        password=request.POST['password']
        profile.update(password=password)


# RTOView
def rto_list(request):
    if request.method=="GET":
        data=RtoConversionModel.objects.filter(profile_id_id=get_id_from_session(request))
        return render(request, 'rto/RTO.html', {'data': data})
    if request.method=="POST" and 'rto_add' in request.POST:
        data = ProfileModel.objects.get(id=get_id_from_session(request))
        rtoseries=request.POST['rtoseries']
        rtoreturn=request.POST['rtoreturn']
        RtoConversionModel.objects.create(rto_series=rtoseries,rto_return=rtoreturn,profile_id=data)
        return redirect('bima_policy:rto')

def update_rto(request,id):
    data={}
    if request.method=="GET":
        data = RtoConversionModel.objects.filter(profile_id_id=get_id_from_session(request))
        udata=RtoConversionModel.objects.filter(id=id)
        return render(request, 'RTO.html',{'data':data,'udata':udata})
    if request.method=='POST':
        if "delete" in request.POST:
            item = get_object_or_404(RtoConversionModel, id=id)
            item.delete()
            return redirect('bima_policy:rto')


# InsuranceView
def ins_comp(request):
    if request.method=="GET":
        try:
            data=InsuranceCompany.objects.filter(profile_id=get_id_from_session(request))
            return render(request,'insurancecompany/insurance_comp.html', {'data':data})
        except ProfileModel.DoesNotExist:
            return render(request,'insurancecompany/insurance_comp.html')
    elif 'company_add' in request.POST:
        try:
            data=ProfileModel.objects.get(id=get_id_from_session(request))
            ins_name=request.POST['inscomp_name']
            status=request.POST['status']
            InsuranceCompany.objects.create(comp_name=ins_name,status=status,profile_id=data)
            return redirect('bima_policy:ins_comp')
        except ProfileModel.DoesNotExist:
            return HttpResponseRedirect(request.path,('bank_det'))

def ins_del(request,id):
    if request.method=='POST' and 'delete' in request.POST:
        data=InsuranceCompany.objects.filter(id=id)
        data.delete()
        return redirect('bima_policy:ins_comp')


# VehicleView
def vehicle_view(request):
    if request.method=="GET":
        try:
            data=VehicleMakeBy.objects.filter(profile_id_id=get_id_from_session(request))
            datamn=VehicleModelName.objects.filter(profile_id_id=get_id_from_session(request))
            datavc=VehicleCategory.objects.filter(profile_id_id=get_id_from_session(request))
            mylist=zip(datamn,data)
            return render(request,'vehicle/vehicle.html',{'list':mylist, 'datavc':datavc, 'data':data,'datamn':datamn})
        except(VehicleMakeBy.DoesNotExist,VehicleModelName.DoesNotExist,VehicleCategory.DoesNotExist):
            return render(request,'vehicle/vehicle.html')
    else:
        p= ProfileModel.objects.get(id=get_id_from_session(request))
        if 'mb_add' in request.POST:
            VehicleMakeBy.objects.create(company=request.POST['makeby'],status = request.POST['mbstatus'],profile_id=p)
            return redirect('bima_policy:vehi')
        elif 'vm_add' in request.POST:

bima_policy/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title> Sign In | Bimabook </title>
	<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><!-- End Required meta tags -->
<!-- FAVICONS -->
<link rel="apple-touch-icon" sizes="144x144" href="static/images/favicon.ico">
<link rel="shortcut icon" href="static/images/favicon.ico">
<meta name="theme-color" content="#3063A0"><!-- End FAVICONS -->
<!-- GOOGLE FONT -->
<link href="https://fonts.googleapis.com/css?family=Fira+Sans:400,500,600" rel="stylesheet"><!-- End GOOGLE FONT -->
<!-- BEGIN PLUGINS STYLES -->
<link rel="stylesheet" href="{% static 'css/aos.css'%}"><!-- END PLUGINS STYLES -->
<!-- BEGIN THEME STYLES -->
<link rel="stylesheet" href="{% static 'css/icofont.min.css' %}"/>
<link rel="stylesheet" href="{% static 'css/theme.min.css'%}" data-skin="default"/>    <!-- BEGIN THEME STYLES -->-
    <link rel="stylesheet" href="{% static 'css/theme.min.css'%}" data-skin="default"/>
    <link rel="stylesheet" href="{% static 'css/theme-dark.min.css'%}" data-skin="dark"/>
    <link rel="stylesheet" href="{% static 'css/custom.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/parsley.css' %}"/>
    <script>
      var skin = localStorage.getItem('skin') || 'default';
      var disabledSkinStylesheet = document.querySelector('link[data-skin]:not([data-skin="' + skin + '"])');
      // Disable unused skin immediately
      disabledSkinStylesheet.setAttribute('rel', '');
      disabledSkinStylesheet.setAttribute('disabled', true);
      // add loading class to html immediately
      document.querySelector('html').classList.add('loading');
    </script><!-- END THEME STYLES -->
  </head>
  <body>
    <!--[if lt IE 10]>
    <div class="page-message" role="alert">You are using an <strong>outdated</strong> browser. Please <a class="alert-link" href="http://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</div>
    <![endif]-->
	<nav class="navbar navbar-expand-lg navbar-light py-3 sticky-header">
        <!-- .container -->
        <div class="container">
          <!-- .hamburger -->
          <button class="hamburger hamburger-squeeze hamburger-light d-flex d-lg-none" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation"><span class="hamburger-box"><span class="hamburger-inner"></span></span></button> <!-- /.hamburger -->
          <!-- .navbar-brand -->
          <a href="index.html" class="navbar-brand ml-auto">
			<img src="{% static 'images/logo.png' %}"  class='img-fluid logo-160' alt='Bimabook Logo'>
          </a> <!-- /.navbar-brand -->
          <a class="navbar-btn btn btn-danger shadow ml-auto order-lg-2" href="" >Back to Home</a>
          <div class="navbar-collapse collapse" id="navbarTogglerDemo01">
            <ul class="navbar-nav mx-auto">
              <li class="nav-item mr-lg-3 active">
                <a class="nav-link py-2" href="index.html#home">Home</a>
              </li>
              <li class="nav-item mr-lg-3">
                <a class="nav-link py-2" href="index.html#feature">Features</a>
              </li>
              <li class="nav-item mr-lg-3">
                <a class="nav-link py-2" href="index.html#pricing">Pricing</a>
              </li>
              <li class="nav-item mr-lg-3">
                <a class="nav-link py-2" href="index.html#about">About</a>
              </li>
              <li class="nav-item mr-lg-3">
                <a class="nav-link py-2" href="index.html#contact">Contact</a>
              </li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
      </nav><!-- /.navbar -->
	<!-- .auth -->
	<main class="auth">
		<header class='mt-6'><h6 class='p-3'>Welcome ! Enter Your Login credentials</h6></header>
		<!-- form -->
		<form data-parsley-validate="true" class="auth-form" id='auth-form' method="POST" action="{%url 'bima_policy:login'%}">
      {% csrf_token %}

      {% if error_message %}
      <div class="alert alert-danger" role="alert">
        <h5 class="alert-heading mx-auto my-auto">{{error_message}}</h5>
      </div>
      {% elif success_message%}
      <div class="alert alert-success " role="alert">
        <h5 class="alert-heading mx-auto my-auto">{{success_message}}</h5>
      </div>
      {% endif %}
  
			<div id="response"></div>
			<!-- .form-group -->
			<div class="form-group">
				<label>User ID<span class='text-danger'>*</span></label>
				<input name="full_name" type="text" data-parsley-required="true" data-parsley-required-message="" value="" class="form-control form-control-lg " id="inputUser" >
			</div><!-- /.form-group -->
			<!-- .form-group -->
			<div class="form-group">
				<label>Password<span class='text-danger'>*</span></label>
				<div class="input-group input-group-lg">
					<input type="password" name="password" data-parsley-required="true" data-parsley-required-message="" value="" class="form-control-lg form-control" id="inputPassword">
					<div class="input-group-prepend">
						<button class="btn btn-reset text-primary px-3" id='btnshowpass' type="button"><i class="icofont-eye-blocked"></i></button>
					</div>
				</div>
			</div>
      <!-- /.form-group -->
			<!-- .form-group -->
			<div class="form-group">
			  <button name="submit" class="btn btn-lg btn-primary btn-block" type="submit" >Sign In</button>
			</div>
      <!-- /.form-group -->
			<!-- .form-group -->
			<div class="form-group text-center">
			  <div class="custom-control custom-control-inline custom-checkbox">
				<input type="checkbox" class="custom-control-input" name="keep_login" id="remember-me" > <label class="custom-control-label" for="remember-me">Keep me sign in</label>
			  </div>
			</div><!-- /.form-group -->
			<!-- recovery links -->
			<div class="text-center pt-3 d-none">
			  <a href="#" class="link">Forgot Username?</a><span class="mx-2">·</span><a href="#" class="link">Forgot Password?</a>
			</div><!-- /recovery links -->
		</form><!-- /.auth-form -->
		<div id='2way-auth'></div>
		<!-- copyright -->
		<footer class="auth-footer"> © 2022 All Rights Reserved. </footer>
    </main><!-- /.auth -->
    {% load static %}
    <!-- BEGIN BASE JS -->
    <script src="{%static 'js/jquery.min.js'%}"></script>
    <script src="{%static 'js/bootstrap.min.js'%}"></script> <!-- END BASE JS -->
    <!-- BEGIN PLUGINS JS -->
    <script src="{%static 'js/particles.js'%}"></script>

	<script src="{%static 'js/popper.min.js'%}"></script>
    <!-- Parsley -->
	<script src="{%static 'js/parsley.js'%}"></script>

    <!-- BEGIN THEME JS -->
    <script src="{% static 'js/theme.js'%}"></script>
    <!-- END THEME JS -->

	<script src="{% static 'js/jquery.form.js'%}"></script>
	<script src="{% static 'js/authenticate6060.js?q=280622'%}"></script>
  </body>

</html>

bima_policy/templates/subscription.html
{%extends "base.html"%}
{%block content%}
{% load static %}
    <main class="app-main"><!-- .app-main -->
        <div class="wrapper"><!-- .wrapper -->
            <div class="page "><!-- .page -->
                <div class="page-inner"> <!-- .page-inner -->
                    <!-- .page-section -->
                    <div class="page-section">
                        <!-- .section-block -->
                        <div class="section-block">
                            <div class="card"><!-- .card -->
                                <div class="card-body"> <!-- .card-body -->
                                    <div class="row">
                                        <div class="col-lg-3 col-md-3">
                                            <label class="">Organization Name: <strong>DEMO</strong></label>
                                        </div>
                                        <div class="col-lg-3 col-md-3">
                                            <label class="">Plan: <strong>Quarterly</strong></label>
                                        </div>
                                        <div class="col-lg-3 col-md-3">
                                            <label class="">Package: <strong>3_GB</strong></label>
                                        </div>
                                        <div class="col-lg-3 col-md-3">
                                            <label class="">Valid Upto: <strong>15/08/2022</strong></label>
                                        </div>
                                    </div>
                                    <hr>
                                    <table id="tblstmt" class="table table-hover no-wrap table-bordered">
                                        <thead>
                                        <tr>
                                            <th class="">Payment Date</th>
                                            <th class="">Amount</th>
                                            <th class="">Transaction No.</th>
                                            <th class="">Plan</th>
                                            <th class="">Valid</th>
                                            <th class="text-center">Invoice</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                            <tr><td>15-May-2022</td><td>0</td><td>000</td><td>Annual</td><td>31-Mar-2022</td><td class="text-center"><a href="invoice.php?q=CfcWVMEwAmt6KDbz+X33osPokyHHdsdW/NmMyM/8m54IuzMGtPj2d9OMfyOkybprlQz8bE95lEa2Ur7jwbRTn4toQxEx7rY6t0gfDN5Kz8Y=" target="_blank" class="text-danger"><i class="icofont-file-pdf"></i></a></td></tr>											</tbody>
                                    </table>
                                </div>
                            </div>
                        </div><!-- /.section-block -->
                    </div><!-- /.page-section -->
                </div><!-- /.page-inner -->
            </div><!-- /.page -->
        </div><!-- /.wrapper -->
  </main><!-- /.app-main -->
<div class="aside-backdrop"></div></div><!-- /.app -->
<div class="modal modal-alert fade" id="ModalAlertError" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="ModalAlertErrorLabel" aria-hidden="true">
<!-- .modal-dialog -->
<div class="modal-dialog" role="document">
  <!-- .modal-content -->
  <div class="modal-content">
    <!-- .modal-header -->
    <div class="modal-header">
        <h5 class="modal-title">
        <i class="fa fa-exclamation-triangle text-red mr-1"></i> System Error </h5>
    </div><!-- /.modal-header -->
    <!-- .modal-body -->
    <div class="modal-body">
      <p>The Code Execution cannot proceed due to system error, retry after refreshing the page if the error remains the same, you need to contact your Administrator immediately.</p>
    </div><!-- /.modal-body -->
    <!-- .modal-footer -->
    <div class="modal-footer">
      <button type="button" class="btn btn-light" data-dismiss="modal">OK</button>
    </div><!-- /.modal-footer -->
  </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script src="{%static 'js/jquery.min.js'%}"></script>
<script src="{%static 'js/popper.min.js'%}"></script>
<script src="{%static 'js/bootstrap.min.js'%}"></script><!-- END BASE JS -->
<!-- BEGIN PLUGINS JS -->
<script src="{% static 'js/pace.min.js' %}"></script>
<script src="{% static 'js/stacked-menu.min.js' %}"></script>
<script src="{% static 'js/perfect-scrollbar.min.js'%}"></script> <!-- END PLUGINS JS -->
<!-- Parsley -->
<script src="{%static 'js/parsley.js'%}"></script></script>
<!-- BEGIN THEME JS -->
<script src="{%static 'js/theme.js' %}"></script> 
<script src="{%static 'js/toastr.min.js' %}"></script>
<script src="{%static 'js/flatpickr.min.js' %}"></script>
<script src="{%static 'js/select2.full.min.js' %}"></script>
<script src="{%static 'js/moment.js' %}"></script>
<script src="{%static 'js/mask-as-number.min.js' %}"></script>
<script src="{%static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{%static 'js/dataTables.bootstrap.js' %}"></script>
<script src="{%static 'js/jquery.form.js' %}"></script>
<script src="{%static 'js/custom.min.js' %}"></script>
<script>
$(document).ready(function(){
    $("#tblstmt1").DataTable({
        "dom": "<'row'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-6'f>>\n  <'table-responsive'tr>\n        <'row align-items-center'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7 d-flex justify-content-end'p>>",
        "language": {
            paginate: {
                previous: '<i class="fa fa-lg fa-angle-left"></i>',
                next: '<i class="fa fa-lg fa-angle-right"></i>'
            },
            infoFiltered: "",
        },
        "columnDefs": [
            {targets: [1,3,4,5],className: "w-10pc text-center"}
        ],
    });
});
</script>

</body></html>
{%endblock%}